// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-credit-cards.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-credit-cards.ts
var search_credit_cards_default = defineTool({
  name: "search_credit_cards",
  title: "Search credit cards",
  description: "Search Finivo's Canadian credit card comparison data by name, issuer, category, annual fee or rewards.",
  inputSchema: {
    query: z.string().trim().optional().describe("Free-text match on card name or issuer."),
    category: z.string().trim().optional().describe("Category filter, e.g. cashback, voyage, etudiant."),
    max_annual_fee: z.number().optional().describe("Only cards with an annual fee at or below this amount."),
    limit: z.number().int().optional().describe("Max number of cards to return (default 10, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, max_annual_fee, limit }) => {
    const supabase = supabaseAnon();
    let q = supabase.from("credit_cards").select(
      "name, issuer, slug, annual_fee, first_year_free, interest_rate, rewards_rate, rewards_type, welcome_bonus, min_income, categories, features, rating, affiliate_link"
    ).eq("is_active", true).order("rating", { ascending: false }).limit(Math.min(Math.max(limit ?? 10, 1), 50));
    if (query) q = q.or(`name.ilike.%${query}%,issuer.ilike.%${query}%`);
    if (category) q = q.contains("categories", [category]);
    if (typeof max_annual_fee === "number") q = q.lte("annual_fee", max_annual_fee);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { cards: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-brokerages.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var search_brokerages_default = defineTool2({
  name: "search_brokerages",
  title: "Search brokerage platforms",
  description: "Search Finivo's comparison of Canadian brokerage and investing platforms.",
  inputSchema: {
    query: z2.string().trim().optional().describe("Free-text match on platform name."),
    level: z2.string().trim().optional().describe("Investor level, e.g. debutant, intermediaire, avance."),
    has_crypto: z2.boolean().optional().describe("Only platforms offering crypto trading."),
    has_options: z2.boolean().optional().describe("Only platforms offering options trading."),
    limit: z2.number().int().optional().describe("Max results (default 10, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, level, has_crypto, has_options, limit }) => {
    const supabase = supabaseAnon();
    let q = supabase.from("brokerage_platforms").select(
      "name, slug, type, transaction_fee_stocks, transaction_fee_etf, monthly_fee, accounts, markets_access, has_options, has_crypto, has_mobile_app, regulation, level, products, strengths, weaknesses, rating, ideal_for, affiliate_link"
    ).eq("is_active", true).order("rating", { ascending: false }).limit(Math.min(Math.max(limit ?? 10, 1), 50));
    if (query) q = q.ilike("name", `%${query}%`);
    if (level) q = q.eq("level", level);
    if (typeof has_crypto === "boolean") q = q.eq("has_crypto", has_crypto);
    if (typeof has_options === "boolean") q = q.eq("has_options", has_options);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { platforms: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-books.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var search_books_default = defineTool3({
  name: "search_books",
  title: "Search finance books",
  description: "Search Finivo's curated library of personal finance and investing books.",
  inputSchema: {
    query: z3.string().trim().optional().describe("Free-text match on title or author."),
    category: z3.string().trim().optional().describe("Book category filter."),
    level: z3.string().trim().optional().describe("Reader level, e.g. beginner, intermediate, advanced."),
    language: z3.string().trim().optional().describe("Book language code, e.g. FR or EN."),
    limit: z3.number().int().optional().describe("Max results (default 10, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, level, language, limit }) => {
    const supabase = supabaseAnon();
    let q = supabase.from("books").select(
      "title, author, slug, category, sub_categories, level, language, short_description, why_read_this_book, reader_profile, themes, quote, rating, affiliate_link, cover_image_url"
    ).eq("is_active", true).limit(Math.min(Math.max(limit ?? 10, 1), 50));
    if (query) q = q.or(`title.ilike.%${query}%,author.ilike.%${query}%`);
    if (category) q = q.eq("category", category);
    if (level) q = q.eq("level", level);
    if (language) q = q.eq("language", language);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { books: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_blog_posts_default = defineTool4({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List published Finivo blog articles with title, slug, excerpt and category.",
  inputSchema: {
    query: z4.string().trim().optional().describe("Free-text match on title or excerpt."),
    category: z4.string().trim().optional().describe("Article category filter."),
    limit: z4.number().int().optional().describe("Max results (default 10, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }) => {
    const supabase = supabaseAnon();
    let q = supabase.from("blog_posts").select(
      "title, title_en, slug, excerpt, excerpt_en, category, tags, author, read_time, published_at, is_featured, cover_image_url"
    ).eq("is_active", true).order("published_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 10, 1), 50));
    if (query) q = q.or(`title.ilike.%${query}%,excerpt.ilike.%${query}%`);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { defineTool as defineTool5, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var get_blog_post_default = defineTool5({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Get the full content of one published Finivo blog article by its slug.",
  inputSchema: {
    slug: z5.string().trim().min(1).describe("The article slug, from list_blog_posts."),
    language: z5.enum(["fr", "en"]).optional().describe("Preferred language (default fr).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug, language }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("blog_posts").select(
      "title, title_en, slug, excerpt, excerpt_en, content, content_en, category, tags, author, read_time, published_at, cover_image_url"
    ).eq("is_active", true).eq("slug", slug).maybeSingle();
    if (error) throw new ToolError(error.message);
    if (!data) throw new ToolError(`No published article found for slug "${slug}".`);
    const en = language === "en";
    const post = {
      ...data,
      title: en && data.title_en || data.title,
      excerpt: en && data.excerpt_en || data.excerpt,
      content: en && data.content_en || data.content
    };
    return {
      content: [{ type: "text", text: JSON.stringify(post) }],
      structuredContent: { post }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "finivo",
  title: "Finivo",
  version: "0.1.0",
  instructions: "Tools for Finivo, a Canadian personal-finance platform. Use `search_credit_cards` to compare Canadian credit cards, `search_brokerages` to compare investing platforms, `search_books` for the curated finance book library, and `list_blog_posts` / `get_blog_post` to read Finivo articles. All data is public and read-only.",
  tools: [search_credit_cards_default, search_brokerages_default, search_books_default, list_blog_posts_default, get_blog_post_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
