-- Add 15 new books to the library (FR/EN), complementing the existing 8
-- Cover images: public/books/covers/{slug}.jpg (sourced via OpenLibrary covers API)
-- Affiliate links: Amazon.ca with Associates tag "finivo20-20"

INSERT INTO public.books (
  slug, title, title_en, author, cover_image_url,
  category, category_en, sub_categories, sub_categories_en,
  level, language,
  short_description, short_description_en,
  full_description, full_description_en,
  why_read_this_book, why_read_this_book_en,
  reader_profile, reader_profile_en,
  themes, themes_en,
  quote, quote_en,
  affiliate_link, affiliate_platform,
  rating, is_featured, is_active
) VALUES

('psychologie-argent', 'La psychologie de l''argent', 'The Psychology of Money', 'Morgan Housel',
 '/books/covers/psychologie-argent.jpg',
 'finance-personnelle', 'personal-finance',
 ARRAY['Comportement', 'Psychologie'], ARRAY['Behavior', 'Psychology'],
 'beginner', 'FR',
 '19 histoires courtes qui révèlent pourquoi notre rapport à l''argent dépend plus de psychologie que de mathématiques.',
 '19 short stories revealing why our relationship with money depends more on psychology than on math.',
 'Morgan Housel démontre, à travers des anecdotes marquantes, que réussir financièrement tient moins à l''intelligence qu''au comportement : patience, humilité et discipline face au hasard.',
 'Through memorable anecdotes, Morgan Housel shows that financial success has less to do with intelligence than with behavior: patience, humility and discipline in the face of randomness.',
 'Pour comprendre les biais psychologiques qui sabotent nos décisions financières et apprendre à investir avec plus de sérénité.',
 'To understand the psychological biases that sabotage our financial decisions and learn to invest with more peace of mind.',
 'Toute personne qui veut mieux comprendre sa propre relation à l''argent, peu importe son niveau de connaissances financières.',
 'Anyone who wants to better understand their own relationship with money, regardless of financial knowledge level.',
 ARRAY['Comportement financier', 'Psychologie de l''investissement', 'Patience', 'Prise de décision'],
 ARRAY['Financial behavior', 'Investing psychology', 'Patience', 'Decision-making'],
 'L''argent est partout, il concerne tout le monde, et pourtant peu de gens en parlent avec honnêteté.',
 'Money is everywhere, it touches nearly everything, and few subjects offer as many lessons if you take the time to study it.',
 'https://www.amazon.ca/dp/2361170566?tag=finivo20-20', 'amazon',
 4.7, true, true),

('homme-plus-riche-babylone', 'L''homme le plus riche de Babylone', 'The Richest Man in Babylon', 'George S. Clason',
 '/books/covers/homme-plus-riche-babylone.jpg',
 'finance-personnelle', 'personal-finance',
 ARRAY['Épargne', 'Classiques'], ARRAY['Saving', 'Classics'],
 'beginner', 'FR',
 'Des paraboles intemporelles situées dans l''ancienne Babylone pour apprendre les bases de l''épargne et de la richesse.',
 'Timeless parables set in ancient Babylon that teach the basics of saving and building wealth.',
 'À travers des récits inspirés de la Babylone antique, Clason enseigne des principes financiers universels : payez-vous en premier, faites fructifier votre argent et protégez votre capital.',
 'Through stories inspired by ancient Babylon, Clason teaches universal financial principles: pay yourself first, make your money work for you, and protect your capital.',
 'Pour assimiler les fondations de la gestion d''argent dans un format narratif simple et mémorable.',
 'To absorb the foundations of money management in a simple, memorable narrative format.',
 'Débutants qui veulent des principes financiers simples, sans jargon technique.',
 'Beginners who want simple financial principles without technical jargon.',
 ARRAY['Épargne', 'Principes financiers', 'Paraboles', 'Fondations'],
 ARRAY['Saving', 'Financial principles', 'Parables', 'Foundations'],
 NULL, NULL,
 'https://www.amazon.ca/dp/2892252628?tag=finivo20-20', 'amazon',
 4.3, false, true),

('barbier-riche', 'Un barbier riche', 'The Wealthy Barber', 'David Chilton',
 '/books/covers/barbier-riche.jpg',
 'finance-personnelle', 'personal-finance',
 ARRAY['Finances personnelles canadiennes', 'Épargne'], ARRAY['Canadian personal finance', 'Saving'],
 'beginner', 'FR',
 'Le classique canadien de la finance personnelle, raconté sous forme de roman par un barbier plein de bon sens.',
 'The Canadian personal finance classic, told as a novel through a plain-spoken, wise barber.',
 'Ray le barbier partage ses conseils pratiques sur les REER, les placements et l''assurance à travers l''histoire de trois amis qui apprennent à gérer leur argent.',
 'Ray the barber shares practical advice on RRSPs, investing and insurance through the story of three friends learning to manage their money.',
 'Pour des bases solides adaptées au contexte financier canadien, présentées de façon accessible.',
 'For solid fundamentals adapted to the Canadian financial context, presented in an accessible way.',
 'Canadiens débutants qui veulent comprendre REER, épargne et placements sans complexité.',
 'Beginner Canadians who want to understand RRSPs, saving and investing without complexity.',
 ARRAY['REER', 'Épargne', 'Contexte canadien', 'Placements'],
 ARRAY['RRSP', 'Saving', 'Canadian context', 'Investing'],
 NULL, NULL,
 'https://www.amazon.ca/dp/2892494338?tag=finivo20-20', 'amazon',
 4.1, false, true),

('argent-ou-vie', 'Votre argent ou votre vie', 'Your Money or Your Life', 'Vicki Robin & Joe Dominguez',
 '/books/covers/argent-ou-vie.jpg',
 'liberte-financiere', 'financial-freedom',
 ARRAY['Indépendance financière', 'Minimalisme'], ARRAY['Financial independence', 'Minimalism'],
 'intermediate', 'FR',
 '9 étapes pour transformer votre rapport à l''argent et atteindre l''indépendance financière.',
 '9 steps to transform your relationship with money and achieve financial independence.',
 'Ce livre fondateur du mouvement FIRE propose une méthode complète pour aligner ses dépenses avec ses valeurs et atteindre la liberté financière plus tôt.',
 'This foundational book of the FIRE movement offers a complete method for aligning spending with values and reaching financial freedom sooner.',
 'Pour repenser en profondeur sa relation au travail, à la consommation et à l''argent.',
 'To deeply rethink your relationship with work, consumption and money.',
 'Personnes prêtes à remettre en question leur mode de vie pour atteindre la liberté financière.',
 'People ready to question their lifestyle in order to reach financial freedom.',
 ARRAY['Indépendance financière', 'FIRE', 'Consommation consciente', 'Budget'],
 ARRAY['Financial independence', 'FIRE', 'Conscious spending', 'Budgeting'],
 NULL, NULL,
 'https://www.amazon.ca/dp/2491492083?tag=finivo20-20', 'amazon',
 4.1, false, true),

('simple-path-wealth', 'La voie ordinaire vers la richesse', 'The Simple Path to Wealth', 'JL Collins',
 '/books/covers/simple-path-wealth.jpg',
 'investissement', 'investment',
 ARRAY['Fonds indiciels', 'Indépendance financière'], ARRAY['Index funds', 'Financial independence'],
 'beginner', 'EN',
 'Une feuille de route simple vers l''indépendance financière grâce aux fonds indiciels à faible coût.',
 'A simple road map to financial independence through low-cost index fund investing.',
 'Né d''une série de lettres à sa fille, ce livre explique pourquoi une stratégie d''investissement simple, basée sur les fonds indiciels, bat la majorité des approches complexes.',
 'Born from a series of letters to his daughter, this book explains why a simple index-fund investing strategy beats most complicated approaches.',
 'Pour investir sereinement sans se noyer dans la sélection de titres individuels.',
 'To invest with confidence without getting lost in individual stock picking.',
 'Débutants en investissement qui veulent une stratégie simple et éprouvée.',
 'Beginner investors who want a simple, proven strategy.',
 ARRAY['Fonds indiciels', 'Investissement passif', 'Indépendance financière', 'Simplicité'],
 ARRAY['Index funds', 'Passive investing', 'Financial independence', 'Simplicity'],
 NULL, NULL,
 'https://www.amazon.ca/dp/1533667926?tag=finivo20-20', 'amazon',
 4.6, true, true),

('random-walk-wall-street', 'Une marche au hasard à travers la Bourse', 'A Random Walk Down Wall Street', 'Burton G. Malkiel',
 '/books/covers/random-walk-wall-street.jpg',
 'investissement', 'investment',
 ARRAY['Théorie financière', 'Marchés efficients'], ARRAY['Financial theory', 'Efficient markets'],
 'intermediate', 'EN',
 'Le guide de référence qui explique pourquoi il est presque impossible de battre le marché à long terme.',
 'The definitive guide explaining why beating the market over the long run is nearly impossible.',
 'Malkiel analyse les différentes théories d''investissement et démontre, données à l''appui, la supériorité de l''investissement indiciel diversifié sur la sélection active de titres.',
 'Malkiel examines competing investment theories and shows, with data, why diversified index investing outperforms active stock picking over time.',
 'Pour comprendre la théorie derrière l''investissement indiciel et éviter les pièges des modes boursières.',
 'To understand the theory behind index investing and avoid the traps of market fads.',
 'Investisseurs intermédiaires qui veulent une base théorique solide.',
 'Intermediate investors who want a solid theoretical foundation.',
 ARRAY['Marchés efficients', 'Investissement indiciel', 'Théorie financière', 'Diversification'],
 ARRAY['Efficient markets', 'Index investing', 'Financial theory', 'Diversification'],
 NULL, NULL,
 'https://www.amazon.ca/dp/0393352242?tag=finivo20-20', 'amazon',
 4.2, false, true),

('common-stocks-uncommon-profits', 'Actions ordinaires et profits extraordinaires', 'Common Stocks and Uncommon Profits', 'Philip A. Fisher',
 '/books/covers/common-stocks-uncommon-profits.jpg',
 'investissement', 'investment',
 ARRAY['Analyse de titres', 'Investissement de croissance'], ARRAY['Stock analysis', 'Growth investing'],
 'advanced', 'EN',
 'La méthode qualitative d''analyse d''entreprises qui a influencé Warren Buffett.',
 'The qualitative company-analysis method that influenced Warren Buffett.',
 'Fisher présente sa célèbre méthode des 15 points pour évaluer la qualité d''une entreprise avant d''investir, au-delà des seuls chiffres financiers.',
 'Fisher lays out his famous 15-point method for evaluating a company''s quality before investing, going beyond the financial statements alone.',
 'Pour apprendre à analyser une entreprise en profondeur, comme le font les meilleurs investisseurs de croissance.',
 'To learn how to analyze a company in depth, the way top growth investors do.',
 'Investisseurs avancés intéressés par l''analyse qualitative d''entreprises.',
 'Advanced investors interested in qualitative company analysis.',
 ARRAY['Analyse qualitative', 'Investissement de croissance', 'Sélection de titres', 'Warren Buffett'],
 ARRAY['Qualitative analysis', 'Growth investing', 'Stock selection', 'Warren Buffett'],
 NULL, NULL,
 'https://www.amazon.ca/dp/0471119288?tag=finivo20-20', 'amazon',
 4.3, false, true),

('millionaire-next-door', 'Le petit millionnaire de la porte d''à côté', 'The Millionaire Next Door', 'Thomas J. Stanley & William D. Danko',
 '/books/covers/millionaire-next-door.jpg',
 'finance-personnelle', 'personal-finance',
 ARRAY['Habitudes des riches', 'Épargne'], ARRAY['Habits of the wealthy', 'Saving'],
 'intermediate', 'EN',
 'Une étude qui révèle que la plupart des millionnaires américains vivent de façon modeste et discrète.',
 'A landmark study revealing that most American millionaires live modestly and quietly.',
 'Stanley et Danko ont interrogé des centaines de millionnaires pour découvrir les sept traits communs qui expliquent leur richesse : discipline, sobriété et épargne constante.',
 'Stanley and Danko surveyed hundreds of millionaires to uncover the seven common traits behind their wealth: discipline, frugality and consistent saving.',
 'Pour déconstruire les idées reçues sur la richesse et adopter des habitudes financières durables.',
 'To debunk myths about wealth and adopt lasting financial habits.',
 'Personnes qui pensent que la richesse s''affiche, et qui veulent revoir leurs habitudes de consommation.',
 'People who think wealth is meant to be shown off, and who want to rethink their spending habits.',
 ARRAY['Habitudes des riches', 'Sobriété', 'Épargne', 'Discipline'],
 ARRAY['Habits of the wealthy', 'Frugality', 'Saving', 'Discipline'],
 NULL, NULL,
 'https://www.amazon.ca/dp/0743420373?tag=finivo20-20', 'amazon',
 4.2, false, true),

('millionaire-fastlane', 'La voie rapide vers la fortune', 'The Millionaire Fastlane', 'MJ DeMarco',
 '/books/covers/millionaire-fastlane.jpg',
 'liberte-financiere', 'financial-freedom',
 ARRAY['Entrepreneuriat', 'Richesse rapide'], ARRAY['Entrepreneurship', 'Fast wealth'],
 'intermediate', 'EN',
 'Une critique du modèle classique ''épargner lentement'' et un plaidoyer pour bâtir la richesse par l''entrepreneuriat.',
 'A critique of the slow-and-steady savings model, and a case for building wealth through entrepreneurship.',
 'DeMarco oppose trois chemins financiers — la voie du trottoir, la voie lente et la voie rapide — et explique comment un système entrepreneurial peut accélérer la création de richesse.',
 'DeMarco contrasts three financial roadmaps — the sidewalk, the slowlane and the fastlane — and explains how building a business system can accelerate wealth creation.',
 'Pour découvrir une perspective entrepreneuriale sur la création de richesse, différente de l''épargne traditionnelle.',
 'To discover an entrepreneurial perspective on wealth creation, different from traditional saving.',
 'Aspirants entrepreneurs qui veulent accélérer leur chemin vers l''indépendance financière.',
 'Aspiring entrepreneurs who want to accelerate their path to financial independence.',
 ARRAY['Entrepreneuriat', 'Création de richesse', 'Systèmes d''affaires', 'Liberté financière'],
 ARRAY['Entrepreneurship', 'Wealth creation', 'Business systems', 'Financial freedom'],
 NULL, NULL,
 'https://www.amazon.ca/dp/0984358102?tag=finivo20-20', 'amazon',
 4.2, false, true),

('zero-to-one', 'De zéro à un', 'Zero to One', 'Peter Thiel',
 '/books/covers/zero-to-one.jpg',
 'business', 'business',
 ARRAY['Startups', 'Innovation'], ARRAY['Startups', 'Innovation'],
 'intermediate', 'FR',
 'Les notes de cours devenues culte de Peter Thiel sur comment bâtir des entreprises qui créent un monopole par l''innovation.',
 'Peter Thiel''s cult class notes on how to build companies that create monopolies through innovation.',
 'Cofondateur de PayPal, Thiel explique pourquoi la vraie création de valeur vient de l''innovation radicale (aller de 0 à 1) plutôt que de la copie de ce qui existe déjà (1 à n).',
 'PayPal co-founder Thiel explains why true value creation comes from radical innovation (going from 0 to 1) rather than copying what already exists (1 to n).',
 'Pour comprendre comment penser la création d''entreprise et l''innovation de façon contrariante.',
 'To understand how to think about company-building and innovation in a contrarian way.',
 'Entrepreneurs et investisseurs intéressés par les startups et l''innovation.',
 'Entrepreneurs and investors interested in startups and innovation.',
 ARRAY['Startups', 'Innovation', 'Monopoles', 'Entrepreneuriat'],
 ARRAY['Startups', 'Innovation', 'Monopolies', 'Entrepreneurship'],
 NULL, NULL,
 'https://www.amazon.ca/dp/2290412082?tag=finivo20-20', 'amazon',
 4.2, false, true),

('reflechissez-devenez-riche', 'Réfléchissez et devenez riche', 'Think and Grow Rich', 'Napoleon Hill',
 '/books/covers/reflechissez-devenez-riche.jpg',
 'mindset', 'mindset',
 ARRAY['Classiques', 'État d''esprit de réussite'], ARRAY['Classics', 'Success mindset'],
 'beginner', 'FR',
 'Le classique intemporel qui a codifié les 13 principes mentaux communs à des centaines de personnes riches.',
 'The timeless classic that codified the 13 mental principles shared by hundreds of wealthy people.',
 'Fruit de plus de 20 ans de recherche auprès de grands entrepreneurs, ce livre présente les principes de désir, de foi et de persistance nécessaires pour transformer ses ambitions en résultats.',
 'The product of more than 20 years of research into successful entrepreneurs, this book lays out the principles of desire, faith and persistence needed to turn ambition into results.',
 'Pour développer un état d''esprit de réussite et une discipline mentale durable.',
 'To develop a success mindset and lasting mental discipline.',
 'Toute personne qui veut renforcer sa motivation et sa discipline face aux objectifs financiers.',
 'Anyone who wants to strengthen their motivation and discipline toward financial goals.',
 ARRAY['Mindset', 'Persistance', 'Réussite', 'Classiques'],
 ARRAY['Mindset', 'Persistence', 'Success', 'Classics'],
 NULL, NULL,
 'https://www.amazon.ca/dp/2290028827?tag=finivo20-20', 'amazon',
 4.2, false, true),

('quatre-accords-tolteques', 'Les Quatre Accords toltèques', 'The Four Agreements', 'Don Miguel Ruiz',
 '/books/covers/quatre-accords-tolteques.jpg',
 'mindset', 'mindset',
 ARRAY['Sagesse pratique', 'Développement personnel'], ARRAY['Practical wisdom', 'Personal growth'],
 'beginner', 'FR',
 'Quatre principes de sagesse toltèque pour se libérer des croyances limitantes qui freinent l''épanouissement personnel et financier.',
 'Four principles of Toltec wisdom for breaking free of limiting beliefs that hold back personal and financial growth.',
 'Don Miguel Ruiz propose un code de conduite simple — parole impeccable, ne rien prendre personnellement, ne pas faire de suppositions, toujours faire de son mieux — pour vivre avec plus de liberté intérieure.',
 'Don Miguel Ruiz offers a simple code of conduct — be impeccable with your word, don''t take anything personally, don''t make assumptions, always do your best — for living with greater inner freedom.',
 'Pour travailler sur les croyances limitantes qui influencent nos décisions, y compris financières.',
 'To work through the limiting beliefs that influence our decisions, including financial ones.',
 'Personnes intéressées par le développement personnel au-delà des finances.',
 'People interested in personal growth beyond finances.',
 ARRAY['Sagesse toltèque', 'Croyances limitantes', 'Liberté intérieure', 'Développement personnel'],
 ARRAY['Toltec wisdom', 'Limiting beliefs', 'Inner freedom', 'Personal growth'],
 NULL, NULL,
 'https://www.amazon.ca/dp/2889116549?tag=finivo20-20', 'amazon',
 4.3, false, true),

('rien-peut-tout-changer', 'Un rien peut tout changer', 'Atomic Habits', 'James Clear',
 '/books/covers/rien-peut-tout-changer.jpg',
 'mindset', 'mindset',
 ARRAY['Habitudes', 'Amélioration continue'], ARRAY['Habits', 'Continuous improvement'],
 'beginner', 'FR',
 'Une méthode éprouvée pour bâtir de bonnes habitudes et éliminer les mauvaises, un petit changement à la fois.',
 'A proven method for building good habits and breaking bad ones, one small change at a time.',
 'James Clear démontre que des améliorations de 1 % répétées jour après jour produisent des résultats extraordinaires, un principe directement applicable à l''épargne et à l''investissement.',
 'James Clear shows that 1% improvements repeated day after day compound into extraordinary results, a principle directly applicable to saving and investing.',
 'Pour créer des habitudes financières durables — épargner, budgéter, investir régulièrement — sans dépendre de la motivation.',
 'To build lasting financial habits — saving, budgeting, investing regularly — without relying on motivation.',
 'Toute personne qui veut transformer ses bonnes intentions financières en actions concrètes et durables.',
 'Anyone who wants to turn good financial intentions into concrete, lasting actions.',
 ARRAY['Habitudes', 'Discipline', 'Amélioration continue', 'Systèmes'],
 ARRAY['Habits', 'Discipline', 'Continuous improvement', 'Systems'],
 'Vous ne montez pas au niveau de vos objectifs, vous descendez au niveau de vos systèmes.',
 'You do not rise to the level of your goals, you fall to the level of your systems.',
 'https://www.amazon.ca/dp/2035969204?tag=finivo20-20', 'amazon',
 4.8, true, true),

('teach-you-rich', 'Je vais vous apprendre à devenir riche', 'I Will Teach You to Be Rich', 'Ramit Sethi',
 '/books/covers/teach-you-rich.jpg',
 'finance-personnelle', 'personal-finance',
 ARRAY['Budget', 'Automatisation'], ARRAY['Budgeting', 'Automation'],
 'beginner', 'EN',
 'Un programme concret de 6 semaines pour automatiser son budget, éliminer ses dettes et investir sans culpabilité.',
 'A concrete 6-week program to automate your budget, crush debt and invest without guilt.',
 'Ramit Sethi propose un système pratique et sans jugement pour mettre en place des comptes bancaires optimisés, automatiser l''épargne et se concentrer sur les grandes décisions financières plutôt que sur les petites privations.',
 'Ramit Sethi offers a practical, judgment-free system for setting up optimized bank accounts, automating savings, and focusing on the big financial decisions instead of small deprivations.',
 'Pour un plan d''action concret et automatisé, sans avoir à couper le café tous les matins.',
 'For a concrete, automated action plan, without having to cut out your daily coffee.',
 'Jeunes professionnels qui veulent un système pratique plutôt qu''une théorie financière.',
 'Young professionals who want a practical system rather than financial theory.',
 ARRAY['Budget automatisé', 'Élimination des dettes', 'Investissement', 'Système financier'],
 ARRAY['Automated budgeting', 'Debt payoff', 'Investing', 'Financial system'],
 NULL, NULL,
 'https://www.amazon.ca/dp/1523505745?tag=finivo20-20', 'amazon',
 4.3, false, true),

('quadrant-cashflow', 'Le Quadrant du Cashflow', 'Rich Dad''s CASHFLOW Quadrant', 'Robert T. Kiyosaki',
 '/books/covers/quadrant-cashflow.jpg',
 'liberte-financiere', 'financial-freedom',
 ARRAY['Revenus passifs', 'Entrepreneuriat'], ARRAY['Passive income', 'Entrepreneurship'],
 'intermediate', 'FR',
 'La suite de Père riche, père pauvre, qui explique les quatre façons de générer un revenu et le chemin vers la liberté financière.',
 'The sequel to Rich Dad Poor Dad, explaining the four ways to earn income and the path to financial freedom.',
 'Kiyosaki présente le quadrant E-S-B-I (Employé, travailleur autonome, propriétaire d''entreprise, investisseur) et explique pourquoi se déplacer vers la droite du quadrant est la clé de la liberté financière.',
 'Kiyosaki presents the E-S-B-I quadrant (Employee, Self-employed, Business owner, Investor) and explains why moving to the right side of the quadrant is key to financial freedom.',
 'Pour comprendre les différentes sources de revenus et identifier sa propre voie vers l''indépendance financière.',
 'To understand the different sources of income and identify your own path to financial independence.',
 'Lecteurs de Père riche, père pauvre qui veulent aller plus loin dans leur réflexion sur le revenu.',
 'Readers of Rich Dad Poor Dad who want to go deeper into their thinking about income.',
 ARRAY['Quadrant E-S-B-I', 'Revenu passif', 'Entrepreneuriat', 'Liberté financière'],
 ARRAY['E-S-B-I quadrant', 'Passive income', 'Entrepreneurship', 'Financial freedom'],
 NULL, NULL,
 'https://www.amazon.ca/dp/2892254744?tag=finivo20-20', 'amazon',
 4.2, false, true);
